// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsjskhqqrneyrwfomkyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zanNraHFxcm5leXJ3Zm9ta3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTU4MTIsImV4cCI6MjA2MTc5MTgxMn0.vQza1XWppK5QsmzFLGGSkuH2CwvQbcjAoGN8gjojbZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);